### ISSUE TITLE
Parser doesn't let the JVM shut down

### ISSUE THREAD

**Issue by BryanBrasil** [uniVocity/univocity-html-parser-api#2]
After running the parser and getting my values the program doesn't exit. I could not debug this as it's obfuscated. All I know is that there there's a few threads with the names of my entities hanging there. 

Can you please help?

**Comment by jbax** [comment]
Done. I'm preparing a new 2.0.1 release to fix this bug and the other one you reported. 

The internal executor service was creating non-daemon threads. As a workaround you can "unblock" your main thread by calling `HtmlParserSettings.getExecutorService().shutDown();`

Thank you for reporting this bug and for using our parser!
